packages:
  - projects/*
  - packages/*
onlyBuiltDependencies:
  - rolldown
catalog:
  '@minecraft/server': 2.4.0-beta.1.21.124-stable
  '@script-bridge/protocol': ^0.4.8
  '@script-bridge/server': ^0.4.8
  '@script-bridge/client': ^0.4.8
