// ⚠️ AUTO-GENERATED FILE
// DO NOT EDIT MANUALLY

export type Arg = string | number;

export type Locale = 'en-US' | 'fr' | 'ja';

export type LangArgs = {
  'command.command.command.description': [];
  'command.command.description': [];
  'command.command.raw.description': [];
  'command.command.sending': [];
  'command.command.silent.description': [];
  'command.command.world.description': [];
  'command.error.catch': [];
  'command.error.nopermission': [];
  'command.error.noworlds': [];
  'command.help.commands': [];
  'command.list.description': [];
  'command.list.players': [];
  'command.list.silent.description': [];
  'command.list.world.description': [];
  'command.panel.create.description': [];
  'command.panel.create.success': [Arg];
  'command.panel.description': [];
  'command.panel.show.description': [];
  'command.panel.show.notFound': [];
  'command.ping.description': [];
  'common.duration': [Arg, Arg, Arg];
  'common.noOnlineWorlds': [];
  'common.worldNotFound': [Arg];
  'console.chat': [Arg, Arg, Arg];
  'console.command': [Arg, Arg, Arg];
  'console.connect': [Arg];
  'console.disconnect': [Arg];
  'console.join': [Arg, Arg];
  'console.leave': [Arg, Arg];
  'console.login': [Arg];
  'console.message': [Arg, Arg, Arg];
  'console.message.withAttachments': [Arg, Arg, Arg];
  'console.reply': [Arg, Arg, Arg, Arg, Arg];
  'console.reply.withAttachments': [Arg, Arg, Arg, Arg, Arg];
  'console.script.ready': [Arg];
  'console.socket.command': [Arg];
  'console.socket.ready': [Arg];
  'death.attack.anvil': [Arg];
  'death.attack.arrow': [Arg, Arg];
  'death.attack.arrow.item': [Arg, Arg, Arg];
  'death.attack.bullet': [Arg, Arg];
  'death.attack.cactus': [Arg];
  'death.attack.cactus.player': [Arg, Arg];
  'death.attack.dehydration': [Arg];
  'death.attack.drown': [Arg];
  'death.attack.drown.player': [Arg, Arg];
  'death.attack.explosion': [Arg];
  'death.attack.explosion.by.bed': [Arg];
  'death.attack.explosion.player': [Arg, Arg];
  'death.attack.fall': [Arg];
  'death.attack.fallingBlock': [Arg];
  'death.attack.fireball': [Arg, Arg];
  'death.attack.fireball.item': [Arg, Arg, Arg];
  'death.attack.fireworks': [Arg];
  'death.attack.flyIntoWall': [Arg];
  'death.attack.freeze': [Arg];
  'death.attack.generic': [Arg];
  'death.attack.inFire': [Arg];
  'death.attack.inFire.player': [Arg, Arg];
  'death.attack.inWall': [Arg];
  'death.attack.indirectMagic': [Arg, Arg];
  'death.attack.indirectMagic.item': [Arg, Arg, Arg];
  'death.attack.lava': [Arg];
  'death.attack.lava.player': [Arg, Arg];
  'death.attack.lightningBolt': [Arg];
  'death.attack.maceSmash.player': [Arg, Arg];
  'death.attack.maceSmash.player.item': [Arg, Arg, Arg];
  'death.attack.magic': [Arg];
  'death.attack.magma': [Arg];
  'death.attack.magma.player': [Arg, Arg];
  'death.attack.mob': [Arg, Arg];
  'death.attack.mob.item': [Arg, Arg, Arg];
  'death.attack.onFire': [Arg];
  'death.attack.onFire.player': [Arg, Arg];
  'death.attack.outOfWorld': [Arg];
  'death.attack.player': [Arg, Arg];
  'death.attack.player.item': [Arg, Arg, Arg];
  'death.attack.sonicBoom': [Arg];
  'death.attack.sonicBoom.player': [Arg, Arg];
  'death.attack.spit': [Arg, Arg];
  'death.attack.stalactite': [Arg];
  'death.attack.stalagmite': [Arg];
  'death.attack.starve': [Arg];
  'death.attack.sulfurCube.hot': [Arg];
  'death.attack.sweetBerry': [Arg];
  'death.attack.thorns': [Arg, Arg];
  'death.attack.thrown': [Arg, Arg];
  'death.attack.thrown.item': [Arg, Arg, Arg];
  'death.attack.trident': [Arg, Arg];
  'death.attack.wither': [Arg];
  'death.fell.accident.generic': [Arg];
  'death.fell.accident.ladder': [Arg];
  'death.fell.accident.vines': [Arg];
  'death.fell.accident.water': [Arg];
  'death.fell.assist': [Arg, Arg];
  'death.fell.assist.item': [Arg, Arg, Arg];
  'death.fell.finish': [Arg, Arg];
  'death.fell.finish.item': [Arg, Arg, Arg];
  'death.fell.killer': [Arg];
  'discord.chat': [Arg, Arg];
  'discord.chat.multipleWorlds': [Arg, Arg, Arg];
  'discord.connect': [];
  'discord.disconnect': [];
  'discord.join': [Arg];
  'discord.leave': [Arg];
  'discord.panel.uptime': [];
  'discord.ready': [];
  'entity.agent.name': [];
  'entity.allay.name': [];
  'entity.area_effect_cloud.name': [];
  'entity.armadillo.name': [];
  'entity.armor_stand.name': [];
  'entity.arrow.name': [];
  'entity.axolotl.name': [];
  'entity.bat.name': [];
  'entity.bee.name': [];
  'entity.blaze.name': [];
  'entity.boat.name': [];
  'entity.bogged.name': [];
  'entity.breeze.name': [];
  'entity.breeze_wind_charge_projectile.name': [];
  'entity.camel.name': [];
  'entity.camel_husk.name': [];
  'entity.cat.name': [];
  'entity.cave_spider.name': [];
  'entity.chest_boat.name': [];
  'entity.chest_minecart.name': [];
  'entity.chest_raft.name': [];
  'entity.chicken.name': [];
  'entity.cod.name': [];
  'entity.command_block_minecart.name': [];
  'entity.copper_golem.name': [];
  'entity.cow.name': [];
  'entity.creaking.name': [];
  'entity.creeper.name': [];
  'entity.dolphin.name': [];
  'entity.donkey.name': [];
  'entity.dragon_fireball.name': [];
  'entity.drowned.name': [];
  'entity.egg.name': [];
  'entity.elder_guardian.name': [];
  'entity.ender_crystal.name': [];
  'entity.ender_dragon.name': [];
  'entity.ender_pearl.name': [];
  'entity.enderman.name': [];
  'entity.endermite.name': [];
  'entity.evocation_fang.name': [];
  'entity.evocation_illager.name': [];
  'entity.eye_of_ender_signal.name': [];
  'entity.falling_block.name': [];
  'entity.fireball.name': [];
  'entity.fireworks_rocket.name': [];
  'entity.fish.clownfish.name': [];
  'entity.fishing_hook.name': [];
  'entity.fox.name': [];
  'entity.frog.name': [];
  'entity.furnace_minecart.name': [];
  'entity.ghast.name': [];
  'entity.glow_squid.name': [];
  'entity.goat.name': [];
  'entity.guardian.name': [];
  'entity.happy_ghast.name': [];
  'entity.hoglin.name': [];
  'entity.hopper_minecart.name': [];
  'entity.horse.name': [];
  'entity.husk.name': [];
  'entity.iron_golem.name': [];
  'entity.item.name': [];
  'entity.leash_knot.name': [];
  'entity.lightning_bolt.name': [];
  'entity.lingering_potion.name': [];
  'entity.llama.name': [];
  'entity.llama_spit.name': [];
  'entity.magma_cube.name': [];
  'entity.minecart.name': [];
  'entity.mooshroom.name': [];
  'entity.moving_block.name': [];
  'entity.mule.name': [];
  'entity.nautilus.name': [];
  'entity.npc.name': [];
  'entity.ocelot.name': [];
  'entity.ominous_item_spawner.name': [];
  'entity.painting.name': [];
  'entity.panda.name': [];
  'entity.parched.name': [];
  'entity.parrot.name': [];
  'entity.phantom.name': [];
  'entity.pig.name': [];
  'entity.piglin.name': [];
  'entity.piglin_brute.name': [];
  'entity.pillager.name': [];
  'entity.player.name': [];
  'entity.polar_bear.name': [];
  'entity.pufferfish.name': [];
  'entity.rabbit.name': [];
  'entity.ravager.name': [];
  'entity.salmon.name': [];
  'entity.sheep.name': [];
  'entity.shulker.name': [];
  'entity.shulker_bullet.name': [];
  'entity.silverfish.name': [];
  'entity.skeleton.name': [];
  'entity.skeleton_horse.name': [];
  'entity.slime.name': [];
  'entity.small_fireball.name': [];
  'entity.sniffer.name': [];
  'entity.snow_golem.name': [];
  'entity.snowball.name': [];
  'entity.spider.name': [];
  'entity.splash_potion.name': [];
  'entity.squid.name': [];
  'entity.stray.name': [];
  'entity.strider.name': [];
  'entity.sulfur_cube.name': [];
  'entity.tadpole.name': [];
  'entity.thrown_trident.name': [];
  'entity.tnt.name': [];
  'entity.tnt_minecart.name': [];
  'entity.trader_llama.name': [];
  'entity.tripod_camera.name': [];
  'entity.tropicalfish.name': [];
  'entity.turtle.name': [];
  'entity.unknown.name': [];
  'entity.vex.name': [];
  'entity.villager.armor': [];
  'entity.villager.butcher': [];
  'entity.villager.cartographer': [];
  'entity.villager.cleric': [];
  'entity.villager.farmer': [];
  'entity.villager.fisherman': [];
  'entity.villager.fletcher': [];
  'entity.villager.leather': [];
  'entity.villager.librarian': [];
  'entity.villager.mason': [];
  'entity.villager.name': [];
  'entity.villager.shepherd': [];
  'entity.villager.tool': [];
  'entity.villager.unskilled': [];
  'entity.villager.weapon': [];
  'entity.villager_v2.name': [];
  'entity.vindicator.name': [];
  'entity.wandering_trader.name': [];
  'entity.warden.name': [];
  'entity.wind_charge_projectile.name': [];
  'entity.witch.name': [];
  'entity.wither.name': [];
  'entity.wither_skeleton.name': [];
  'entity.wither_skull.name': [];
  'entity.wither_skull_dangerous.name': [];
  'entity.wolf.name': [];
  'entity.xp_bottle.name': [];
  'entity.xp_orb.name': [];
  'entity.zoglin.name': [];
  'entity.zombie.name': [];
  'entity.zombie_horse.name': [];
  'entity.zombie_nautilus.name': [];
  'entity.zombie_pigman.name': [];
  'entity.zombie_villager.name': [];
  'entity.zombie_villager_v2.name': [];
  'minecraft.connect': [Arg];
  'minecraft.message': [Arg, Arg];
  'minecraft.message.withAttachments': [Arg, Arg];
  'minecraft.reply': [Arg, Arg, Arg, Arg];
  'minecraft.reply.withAttachments': [Arg, Arg, Arg, Arg];
};

export type LangKey = keyof LangArgs;
