export enum ActionId {
  WorldInitialize = 'dm:world_initialize',
  SendMessage = 'dm:send_message',
  RunCommand = 'dm:run_command',
  SendScriptEvent = 'dm:send_script_event',
  GetTPS = 'dm:get_tps',
  GetEntityLocation = 'dm:get_entity_location',
  GetEntityDimension = 'dm:get_entity_dimension',
  GetGameMode = 'dm:get_game_mode',
  SetGameMode = 'dm:set_game_mode',
  SetTitle = 'dm:set_title',
  UpdateSubtitle = 'dm:update_subtitle',
  SetActionBar = 'dm:set_action_bar',
  KickPlayer = 'dm:kick_player',
  PlayerJoin = 'dm:player_join',
  PlayerLeave = 'dm:player_leave',
  ChatSend = 'dm:chat_send',
  GetScore = 'dm:get_score',
  UpdateScore = 'dm:update_score',
  GetAllScores = 'dm:get_all_scores',
  RemoveParticipant = 'dm:remove_participant',
  GetObjective = 'dm:get_objective',
  GetAllObjectives = 'dm:get_all_objectives',
  UpdateObjective = 'dm:update_objective',
  SetObjectiveDisplay = 'dm:set_objective_display',
}
