export enum ActionId {
  WorldInitialize = 'dm:world_initialize',
  SendMessage = 'dm:send_message',
  RunCommand = 'dm:run_command',
  GetPlayers = 'dm:get_players',
  GetEntityLocation = 'dm:get_entity_location',
  GetGameMode = 'dm:get_game_mode',
  SetGameMode = 'dm:set_game_mode',
  SetTitle = 'dm:set_title',
  UpdateSubtitle = 'dm:update_subtitle',
  SetActionBar = 'dm:set_action_bar',
  PlayerJoin = 'dm:player_join',
  PlayerLeave = 'dm:player_leave',
  ChatSend = 'dm:chat_send',
}
