name: Deploy Docs

on:
  push:
    branches:
      - main
      - rewrite
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-docs
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        run: pnpm --filter @discord-mcbe/docs build

      - name: Deploy Docs
        working-directory: ./projects/docs
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: pnpm exec wrangler deploy
