name: On Push
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.4.0'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Check
        run: pnpm run check

      - name: Test launcher
        working-directory: ./projects/launcher
        run: pnpm run test
